database:
  url: jdbc:mysql://localhost:3306/market_flutter?autoReconnect=true&useSSL=false
  username: flutter
  password: 60C9831D-0CC9-46D1-AE8B-BE648ACF7F2D

binance:
  api-key: tbd
  secret-key: tbd
  api-url: https://api.binance.com