branch-defaults:
  default:
    environment: market-flutter-prod
  main:
    environment: null
    group_suffix: null
deploy:
  artifact: target/api-0.0.1.jar
global:
  application_name: market-flutter
  branch: null
  default_ec2_keyname: aws-eb-market-flutter
  default_platform: Corretto 17 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
